title: "Edson OliveiraJr"
description: "Associate Professor of Software Engineering"
url: "https://edson-ao-junior.github.io"
baseurl: ""

remote_theme: "academicpages/academicpages.github.io"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

author:
  name: "Edson OliveiraJr"
  avatar: "/assets/images/profile.jpg"
  bio: "Associate Professor of Software Engineering"
  location: "Brazil"
  employer: "State University of Maring√° (UEM)"
  email: "oliveirajr.edson@gmail.com"

social:
  googlescholar: "https://scholar.google.com/citations?user=71vteVgAAAAJ" 
  orcid: "0000-0002-4760-1626"
  github: edson-ao-junior
  dblp: "https://dblp.org/pid/04/2051.html"

markdown: kramdown
