title: "Edson OliveiraJr"
description: "Associate Professor of Software Engineering"
url: "https://edson-ao-junior.github.io"
baseurl: ""

remote_theme: academicpages/academicpages.github.io

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

collections:
  pages:
    output: true
    permalink: /:name/

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-S0QJ65TVF7"
    anonymize_ip: true
